#!/usr/bin/env node
/**
 * 将字体文件转换为 base64 并嵌入到代码中
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const fontPath = join(__dirname, '..', 'font', 'PingFangMengMeng-2.ttf');
const outputPath = join(__dirname, '..', 'src', 'defaultFont.ts');

console.log('Reading font file...');
const fontBuffer = readFileSync(fontPath);
const base64 = fontBuffer.toString('base64');

console.log(`Font size: ${(fontBuffer.length / 1024 / 1024).toFixed(2)} MB`);
console.log(`Base64 size: ${(base64.length / 1024 / 1024).toFixed(2)} MB`);

const output = `// Auto-generated file, do not edit manually
// Generated by scripts/embed-font.js

export const DEFAULT_FONT_BASE64 = "${base64}";

export function getDefaultFontBuffer(): Uint8Array {
  const binaryString = atob(DEFAULT_FONT_BASE64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}
`;

writeFileSync(outputPath, output);
console.log(`✓ Generated ${outputPath}`);
